<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <Target Name="MergePackageDependencies" AfterTargets="Build" Condition="'$(DesignTimeBuild)' != 'true' And Exists('$(TargetDir)LukeSkywalker.IPNetwork.dll')">
    <ItemGroup>
      <ILRepackInputAssemblies Include="$(TargetPath)" />
      <ILRepackInputAssemblies Include="$(TargetDir)LukeSkywalker.IPNetwork.dll" />
    </ItemGroup>

    <ILRepack
      Parallel="true"
      DebugInfo="true"
      Internalize="true"
      InputAssemblies="@(ILRepackInputAssemblies)"
      OutputFile="$(TargetPath)"
      TargetKind="SameAsPrimaryAssembly"
      LibraryPath="$(TargetDir);$(BEPINEX_CORE);$(VALHEIM_MANAGED);$(PUBLICIZED_PATH)" />

    <Delete Files="$(TargetDir)LukeSkywalker.IPNetwork.dll" />
  </Target>

</Project>
